{% set name = "sqlite-utils" %}
{% set version = "3.35" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlite-utils-{{ version }}.tar.gz
  sha256: 8f6fe7f8d12772cd5cf4594703a98dcd0c37c0fd6820dd20541ba74b9fca363a

build:
  entry_points:
    - sqlite-utils = sqlite_utils.cli:cli
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click
    - click-default-group-wheel
    - python >=3.7
    - python-dateutil
    - sqlite-fts4
    - tabulate

test:
  source_files:
    - tests
  imports:
    - sqlite_utils
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys -k 'not commands_are_documented and not recipes_are_documented and not insert_streaming_batch_size_1 and not cli_bulk_batch_size' tests
  requires:
    - cogapp
    - hypothesis
    - pip
    - pytest

about:
  home: https://github.com/simonw/sqlite-utils
  summary: CLI tool and Python utility functions for manipulating SQLite databases
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - simonw
    - thewchan
